// supabase-config.js
const supabaseUrl = 'https://fuyqsdolsyfnoxdwikmw.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eXFzZG9sc3lmbm94ZHdpa213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MjMzODYsImV4cCI6MjA1MTE5OTM4Nn0._LSYoM3JcRxKod-NEtclxlrluHvjbWON29mP1IbGTcY'
const supabaseClient = supabaseJs.createClient(supabaseUrl, supabaseKey)